name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Use OCaml 4.12.x
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: 4.12.x
          dune-cache: true

      - run: opam depext uri

      - run: opam install uri --verbose
