name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Use OCaml 4.12.x
        uses: actions-ml/setup-ocaml@master
        with:
          ocaml-version: 4.12.x

      - run: opam pin add dune.dev https://github.com/smorimoto/dune.git#windows-race-condition

      - run: echo "DUNE_CACHE=enabled" >>"$GITHUB_ENV"

      - run: echo "DUNE_CACHE_TRANSPORT=direct" >>"$GITHUB_ENV"

      - run: opam depext uri

      - run: opam install uri --verbose
